# Generated by Django 2.0.1 on 2019-04-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_defectsreported_testcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectsreported',
            name='date',
            field=models.CharField(default='cy', max_length=32),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='date',
            field=models.CharField(default='cy', max_length=32),
        ),
    ]
